import { useCallback,useEffect,useMemo,useState } from "react";
const API="http://127.0.0.1:8002";const ACTIVE_CASE_KEY="iios.activeCaseId";
type CaseRow={case_id:string;topic?:string;ticker?:string;health?:string;committee_disposition?:string;committee_confidence?:number;evidence_quality?:number;latest_evidence_count?:number;latest_action?:string;latest_return_pct?:number;monitoring_enabled?:boolean;latest_reunderwrite_disposition?:string;latest_reunderwrite_confidence?:number};
type History={signal_ladder?:{current_stage?:string;next_requirements?:string[]};timeline?:Array<Record<string,unknown>>};
type Factory={portfolio?:{nav?:number|null;cash?:number|null;positions?:number|null;return_pct?:number|null;drawdown_pct?:number|null};safety?:{all_invariants?:boolean;live_execution?:boolean};activity?:{recent_event_count?:number;latest_event?:{event_type?:string;created_at?:string;room?:string}}};
type Capital={stage?:string;research?:{qualified_buy_candidate?:boolean;unmet_requirements?:string[]};capital?:{decision?:string;failed_hard_checks?:string[]};permissions?:{position_sizing_ready?:boolean;paper_authorization_ready?:boolean;paper_order_permission?:boolean;live_execution?:boolean}};
type State={cases:CaseRow[];history:History|null;factory:Factory|null;capital:Capital|null;online:boolean;caseId:string|null};
const label=(v?:string)=>String(v||"UNKNOWN").replaceAll("_"," ");const pct=(v?:number|null)=>v==null?"—":`${Math.round(v*100)}%`;const money=(v?:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const tone=(v?:string)=>{const s=String(v||"").toUpperCase();if(/BROKEN|INVALID|REJECT|BLOCK|NO_TRADE|LOCK|FAIL/.test(s))return"iios-state-block";if(/WATCH|PENDING|EARLY|WAIT|REUNDERWRITE|MATERIAL/.test(s))return"iios-state-watch";if(/INTACT|CLEAR|QUALIFIED|APPROVED|READY|HEALTHY/.test(s))return"iios-state-clear";return"iios-state-idle";};
function journeyStage(active:CaseRow|null,history:History|null,capital:Capital|null){const s=String(history?.signal_ladder?.current_stage||"").toUpperCase();if(capital?.permissions?.paper_order_permission)return 5;if(capital?.permissions?.position_sizing_ready||/RISK|QUALIFIED|BUY/.test(s))return 4;if(active?.committee_disposition)return 3;if(active?.evidence_quality!=null)return 2;return 1;}
export default function ExecutiveShowcase(){const[state,setState]=useState<State>({cases:[],history:null,factory:null,capital:null,online:false,caseId:window.localStorage.getItem(ACTIVE_CASE_KEY)});
 const load=useCallback(async()=>{const caseId=window.localStorage.getItem(ACTIVE_CASE_KEY);try{const[d,f]=await Promise.all([fetch(`${API}/monitoring/dashboard`),fetch(`${API}/factory-room/status`)]);if(!d.ok||!f.ok)throw new Error();const dashboard=await d.json() as{cases?:CaseRow[]};const factory=await f.json() as Factory;let history:History|null=null,capital:Capital|null=null;if(caseId){const[h,c]=await Promise.all([fetch(`${API}/history/${caseId}`),fetch(`${API}/paper-capital/${caseId}/status`)]);if(h.ok)history=await h.json() as History;if(c.ok)capital=await c.json() as Capital;else if(c.status===409)capital={stage:"RESEARCH_INPUTS_PENDING",permissions:{position_sizing_ready:false,paper_authorization_ready:false,paper_order_permission:false,live_execution:false}};}setState({cases:dashboard.cases||[],history,factory,capital,online:true,caseId});}catch{setState(x=>({...x,online:false,caseId}));}},[]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t);},[load]);
 const active=useMemo(()=>state.cases.find(x=>x.case_id===state.caseId)??null,[state.cases,state.caseId]);const signal=state.history?.signal_ladder?.current_stage;const next=state.history?.signal_ladder?.next_requirements?.[0]||active?.latest_action||"Continue governed monitoring";const latestEvent=state.factory?.activity?.latest_event;const changed=latestEvent?.event_type?`${label(latestEvent.event_type)}${latestEvent.room?` in ${label(latestEvent.room)}`:""}`:active?.latest_action||"No recent canonical event in the live activity window";const why=active?`${active.ticker||"Selected case"} is ${label(signal||active.health)} with Committee ${label(active.committee_disposition)} at ${pct(active.committee_confidence)} confidence and ${pct(active.evidence_quality)} evidence quality.`:"Select an active case to generate an executive thesis briefing.";const stage=journeyStage(active,state.history,state.capital);const portfolio=state.factory?.portfolio;const capitalLocked=state.factory?.safety?.live_execution===false;
 return <section className="executive-showcase"><div className="exec-hero"><div><div className="exec-eyebrow">IIOS · EXECUTIVE VIEW</div><h1>{active?.ticker||"INTELLIGENCE FACTORY"} <span className={tone(signal||active?.health)}>{active?`· ${label(signal||active.health)}`:""}</span></h1><p>{active?.topic||"A governed, evidence-backed operating view of the Investment Intelligence OS."}</p></div><div className={state.online?"exec-live":"exec-offline"}>{state.online?"LIVE OPERATING STATE":"TELEMETRY OFFLINE"}</div></div>
 <div className="exec-brief-grid"><article><span>WHAT CHANGED</span><strong>{changed}</strong><small>{latestEvent?.created_at||"No recent timestamp"}</small></article><article><span>WHY IT MATTERS</span><strong>{why}</strong></article><article><span>WHAT HAPPENS NEXT</span><strong>{next}</strong></article></div>
 <div className="exec-boardroom"><div className="exec-boardroom-primary"><div><span>THESIS</span><strong className={tone(signal||active?.health)}>{label(signal||active?.health)}</strong></div><div><span>COMMITTEE</span><strong className={tone(active?.committee_disposition)}>{label(active?.committee_disposition)}</strong></div><div><span>CONFIDENCE</span><strong>{pct(active?.committee_confidence)}</strong></div><div><span>EVIDENCE</span><strong>{pct(active?.evidence_quality)}{active?.latest_evidence_count!=null?` · ${active.latest_evidence_count} items`:""}</strong></div><div><span>CAPITAL</span><strong className={capitalLocked?"iios-state-block":tone(state.capital?.stage)}>{capitalLocked?"LIVE LOCKED":label(state.capital?.stage)}</strong></div></div>
 <div className="exec-boardroom-secondary"><div><span>PAPER NAV</span><strong>{money(portfolio?.nav)}</strong></div><div><span>CASH</span><strong>{money(portfolio?.cash)}</strong></div><div><span>POSITIONS</span><strong>{portfolio?.positions??"—"}</strong></div><div><span>PORTFOLIO RETURN</span><strong>{portfolio?.return_pct==null?"—":pct(portfolio.return_pct)}</strong></div><div><span>DRAWDOWN</span><strong>{portfolio?.drawdown_pct==null?"—":pct(portfolio.drawdown_pct)}</strong></div><div><span>CASE RETURN</span><strong>{active?.latest_return_pct==null?"—":pct(active.latest_return_pct)}</strong></div></div></div>
 <div className="exec-journey"><div className="exec-journey-title"><span>GOVERNED CASE JOURNEY</span><strong>Real state only · no simulated movement</strong></div><div className="exec-journey-steps">{[["Evidence","Source-backed inputs"],["8 Desks","Specialist analysis"],["Committee","Disposition & confidence"],["Risk","Deterministic controls"],["Paper","Capital authorization"],["Monitor","Thesis integrity"]].map(([name,desc],i)=>{const n=i+1;const complete=n<stage;const activeStep=n===stage;return <div key={name} className={`exec-step ${complete?"complete":""} ${activeStep?"active":""}`}><span>{n}</span><strong>{name}</strong><small>{desc}</small></div>})}</div></div>
 <div className="exec-safety"><div><span>SAFETY INVARIANTS</span><strong className={state.factory?.safety?.all_invariants?"iios-state-clear":"iios-state-watch"}>{state.factory?.safety?.all_invariants?"HOLDING":"VERIFY"}</strong></div><div><span>LIVE EXECUTION</span><strong className="iios-state-block">{capitalLocked?"LOCKED":"NOT VERIFIED"}</strong></div><div><span>BOARDROOM TAKEAWAY</span><strong>{active?`${active.ticker||"Case"}: ${label(signal||active.health)} · ${label(active.committee_disposition)} · next: ${next}`:"Select a case for boardroom takeaway."}</strong></div></div></section>;
}
