import { useCallback,useEffect,useMemo,useState } from "react";
import { getActiveCaseId, subscribeActiveCase } from "./activeCaseStore";
const API="http://127.0.0.1:8002";
type Entry={judgment_entry_id?:string;postmortem_id?:string;case_id?:string;agent_key?:string;agent?:string;original_disposition?:string;original_confidence?:number;outcome?:string;correct?:boolean|null;calibration_score?:number;realized_return_pct?:number|null;created_at?:string};type Bank={case_id:string;judgment_entries?:Entry[];postmortems?:Array<Record<string,unknown>>;thesis_monitors?:Array<Record<string,unknown>>;reunderwrites?:Array<Record<string,unknown>>};
const pct=(v?:number|null)=>v==null?"—":`${Math.round(v*100)}%`;const short=(v?:string)=>v?`${v.slice(0,7)}…${v.slice(-5)}`:"—";
export default function JudgmentLibraryBrowser(){const[bank,setBank]=useState<Bank|null>(null),[query,setQuery]=useState(""),[online,setOnline]=useState(false),[caseId,setCaseId]=useState<string|null>(()=>getActiveCaseId());const load=useCallback(async()=>{const id=getActiveCaseId();try{if(!id){setBank(null);setOnline(true);return;}const r=await fetch(`${API}/judgment-bank/${id}`);if(!r.ok)throw new Error();setBank(await r.json() as Bank);setOnline(true);}catch{setOnline(false);}},[]);
 useEffect(()=>subscribeActiveCase(id=>{setCaseId(id);window.setTimeout(()=>void load(),0);}),[load]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const t=window.setInterval(()=>void load(),10000);return()=>{window.clearTimeout(initial);window.clearInterval(t);};},[load]);
 const entries=useMemo(()=>bank?.judgment_entries||[],[bank]);const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return entries;return entries.filter(e=>[e.agent,e.agent_key,e.outcome,e.original_disposition,e.postmortem_id].some(v=>String(v||"").toLowerCase().includes(q)));},[entries,query]);const calibrated=entries.filter(e=>e.calibration_score!=null).length;const correct=entries.filter(e=>e.correct===true).length;const decisive=entries.filter(e=>e.correct!==null&&e.correct!==undefined).length;
 return <section className="judgment-library"><div className="judgment-library-head"><div><div className="judgment-library-eyebrow">GOVERNED JUDGMENT LIBRARY</div><h2>{caseId?"Selected Case Judgment":"No Case Selected"}</h2><p>Outcome-linked judgment entries retain case, post-mortem, agent, confidence, realized outcome, and calibration provenance.</p></div><div className={online?"iios-state-clear":"iios-state-block"}>{online?"LIBRARY ONLINE":"LIBRARY OFFLINE"}</div></div><div className="judgment-library-metrics"><div><span>ENTRIES</span><strong>{entries.length}</strong></div><div><span>CALIBRATED</span><strong>{calibrated}</strong></div><div><span>DECISIVE</span><strong>{decisive}</strong></div><div><span>CORRECT</span><strong>{correct}</strong></div><div><span>REUNDERWRITES</span><strong>{bank?.reunderwrites?.length||0}</strong></div></div><div className="judgment-library-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search agent, outcome, disposition, provenance…"/><span>{filtered.length} visible</span></div><div className="judgment-library-table"><table><thead><tr><th>AGENT</th><th>CALL</th><th>CONFIDENCE</th><th>OUTCOME</th><th>CALIBRATION</th><th>PROVENANCE</th></tr></thead><tbody>{filtered.map((e,i)=><tr key={e.judgment_entry_id||i}><td><strong>{e.agent||e.agent_key||"Unknown"}</strong><small>{e.agent_key}</small></td><td>{e.original_disposition||"—"}</td><td>{pct(e.original_confidence)}</td><td><span className={e.correct===true?"iios-state-clear":e.correct===false?"iios-state-block":"iios-state-idle"}>{e.outcome||"—"}</span></td><td>{pct(e.calibration_score)}</td><td><small title={e.postmortem_id}>{short(e.postmortem_id)}</small></td></tr>)}{!filtered.length&&<tr><td colSpan={6}>No matching governed judgment entries for the selected case.</td></tr>}</tbody></table></div><div className="judgment-library-provenance"><span>PROVENANCE LINEAGE</span><strong>Case → Agent Result → Post-Mortem → Judgment Entry → Scorecard</strong></div></section>}
