import { useEffect, useState } from "react";
import CinematicCharacterPortrait from "./CinematicCharacterPortrait";
import ExpansionWing from "./ExpansionWing";
import { mapEventToScene, maxNarration, type Scene } from "./EventSceneMapper";
import LivingWallGalleryStatus from "./LivingWallGalleryStatus";
import { loadFactoryTruth, selectGalleryTruth, type TruthRecord, type TruthResult } from "./TruthSourceAdapter";
import UnifiedCommandCenter from "./UnifiedCommandCenter";
import "./LivingWallApp.css";
import "./LivingWallArtDirection.css";
import "./LivingWallMobile.css";

type Mode = "gallery" | "story" | "replay" | "command" | "expansion";
const MODES: Array<[Mode, string]> = [["gallery", "Gallery"], ["story", "Story"], ["replay", "Replay"], ["command", "Command"], ["expansion", "Expansion Wing"]];
const CAST = ["policy", "macro", "fundamentals", "market_structure", "commodities", "geo_weather", "skeptic", "portfolio"] as const;

function record(value: unknown): TruthRecord { return value && typeof value === "object" && !Array.isArray(value) ? value as TruthRecord : {}; }
function rows(value: unknown): TruthRecord[] { return Array.isArray(value) ? value.filter((item): item is TruthRecord => Boolean(item) && typeof item === "object" && !Array.isArray(item)) : []; }
function text(value: unknown, fallback = "UNKNOWN"): string { return typeof value === "string" && value.trim() ? value.trim() : fallback; }
function date(value: unknown): string { const parsed = typeof value === "string" ? new Date(value) : null; return parsed && !Number.isNaN(parsed.getTime()) ? parsed.toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "UNKNOWN"; }

export default function LivingWallApp() {
  const [mode, setMode] = useState<Mode>("gallery");
  const [truth, setTruth] = useState<TruthResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [paused, setPaused] = useState(false);
  const [index, setIndex] = useState(0);
  const [rotation, setRotation] = useState(false);
  useEffect(() => { let disposed = false; const load = async () => { try { const next = await loadFactoryTruth(); if (!disposed) { setTruth(next); setError(null); } } catch { if (!disposed) setError("Canonical truth and sanitized fallback are unavailable."); } }; void load(); const timer = window.setInterval(() => void load(), 15_000); return () => { disposed = true; window.clearInterval(timer); }; }, []);
  const layers = record(record(truth?.data.validation).layers);
  const telemetry = record(layers.factory_telemetry);
  const payload = record(telemetry?.payload);
  const events = rows(payload.recent_meaningful_events ?? payload.recent_events);
  const galleryTruth = selectGalleryTruth(truth, error);
  const degraded = galleryTruth.degraded;
  const selected = events[index] ?? null;
  const scene = mapEventToScene(selected, degraded);
  const degradedMessage = error
    ?? (truth?.fallback
      ? "Canonical truth is unavailable; this wall is using sanitized fallback telemetry."
      : "Canonical truth is stale, unavailable, or internally inconsistent.");
  useEffect(() => { if (!rotation || paused) return; const timer = window.setInterval(() => setMode(mode === "gallery" ? "story" : "gallery"), 20_000); return () => window.clearInterval(timer); }, [mode, paused, rotation]);
  const pauseRotation = () => { if (rotation) setRotation(false); };
  if (mode === "command") return <div className="wall-command" onClick={pauseRotation}><WallNav mode={mode} paused={paused} setMode={setMode} setPaused={setPaused} setRotation={setRotation}/><UnifiedCommandCenter/></div>;
  return <div className={`wall-shell ${paused ? "wall-paused" : ""}`} onClick={pauseRotation}><WallNav mode={mode} paused={paused} setMode={setMode} setPaused={setPaused} setRotation={setRotation}/>{degraded ? <div className="wall-degraded" role="alert"><strong>DATA DEGRADED</strong><span>{degradedMessage}</span></div> : null}{mode === "gallery" && <Gallery scene={scene} galleryTruth={galleryTruth} events={events} rotation={rotation} setRotation={setRotation}/>} {mode === "story" && <Story scene={scene} truth={truth} events={events} index={index} setIndex={setIndex}/>} {mode === "replay" && <Replay events={events} index={index} setIndex={setIndex}/>} {mode === "expansion" && <ExpansionWing/>}</div>;
}

function WallNav({ mode, paused, setMode, setPaused, setRotation }: { mode: Mode; paused: boolean; setMode: (mode: Mode) => void; setPaused: (paused: boolean) => void; setRotation: (value: boolean) => void }) { return <header className="wall-nav"><div><span>IIOS LIVING WALL</span><strong>THE FAMILY FACTORY</strong></div><nav aria-label="Living Wall modes">{MODES.map(([key, name]) => <button key={key} className={mode === key ? "is-active" : ""} onClick={() => { setRotation(false); setMode(key); }}>{name}</button>)}</nav><button className="wall-pause" onClick={() => setPaused(!paused)} aria-pressed={paused}>{paused ? "Resume scene" : "Pause scene"}</button></header>; }
function FactoryStage({ scene, historical = false }: { scene: Scene; historical?: boolean }) { const rooms = ["radar", "research", "agents", "committee", "risk", "paper", "monitoring", "learning", "watch"]; return <section className={`wall-cutaway wall-cutaway--${scene.lighting} ${historical ? "wall-cutaway--historical" : ""}`} aria-label="IIOS cutaway factory"><div className="wall-roof"><span>IIOS PRIVATE INTELLIGENCE FACTORY</span><b>{historical ? "ARCHIVE LIGHTING / HISTORICAL" : "EVIDENCE GOVERNED / READ ONLY"}</b></div><div className="wall-floor"><div className="wall-route" aria-hidden="true">{rooms.slice(0, 8).map((room, index) => <i key={room} className={scene.animate && index <= rooms.indexOf(scene.room) ? "is-lit" : ""} />)}</div>{rooms.map((room) => <article key={room} className={`wall-room wall-room--${room} ${scene.room === room ? "is-focused" : ""} ${scene.room === "watch" && room !== "watch" ? "is-frozen" : ""}`}><span>{room === "watch" ? "FACTORY WATCH" : room.toUpperCase()}</span><small>{scene.room === room ? "FOCUS" : scene.room === "watch" ? "FROZEN / RECEIPT" : "STANDING BY"}</small><div className="wall-window" /></article>)}<div className="wall-expansion-seal"><span>EXPANSION WING</span><b>SEALED</b><small>REGISTRY ONLY</small></div><div className="wall-character wall-character--max"><CinematicCharacterPortrait characterKey="max" variant="boss" /></div>{CAST.map((key, index) => <div key={key} className={`wall-character wall-character--agent-${index + 1}`}><CinematicCharacterPortrait characterKey={key} variant="scene" active={scene.character === key} /></div>)}</div><div className="wall-foundation"><span>NO LIVE EXECUTION</span><span>RECEIPTS ANCHOR THE FLOOR</span><span>QUIET IS A VALID STATE</span></div></section>; }
function Gallery({ scene, galleryTruth, events, rotation, setRotation }: { scene: Scene; galleryTruth: ReturnType<typeof selectGalleryTruth>; events: TruthRecord[]; rotation: boolean; setRotation: (value: boolean) => void }) { return <main className={`wall-gallery wall-gallery--${scene.room}`}><FactoryStage scene={scene}/><LivingWallGalleryStatus activeRoom={scene.room === "watch" ? "FACTORY WATCH" : scene.room.toUpperCase()} truth={galleryTruth}/><section className="wall-scene-caption"><div><span>{scene.historical ? "HISTORICAL PRESENTATION" : "LATEST VERIFIED EVENT"}</span><h1>{scene.room === "watch" ? "The factory is investigating" : scene.title}</h1><p>{maxNarration(scene)}</p><b>{scene.animate ? "RECEIPT ANCHORED" : "MOVEMENT WITHHELD"} · {text(scene.receipt.case_id, "NO CASE LINEAGE")}</b></div><footer><span>{events.length ? `${events.length} sanitized receipts available` : "No verified current event; the wall is calm."}</span><button className="wall-rotation" data-rotation-control onClick={(event) => { event.stopPropagation(); setRotation(!rotation); }} aria-pressed={rotation}>{rotation ? "Rotation on" : "Start rotation"}</button></footer></section></main>; }
function Story({ scene, truth, events, index, setIndex }: { scene: Scene; truth: TruthResult | null; events: TruthRecord[]; index: number; setIndex: (value: number) => void }) { return <main className="wall-story"><FactoryStage scene={scene} historical={scene.historical}/><section className="wall-story-overlay"><span>MARKET DAY STORY / VERIFIED SCENES ONLY</span><h1>{scene.room === "idle" ? "The factory is reviewing incomplete evidence" : scene.title}</h1><p>{maxNarration(scene)}</p><div className="wall-story-actions"><button disabled={!index} onClick={() => setIndex(index - 1)}>Previous scene</button><button disabled={index >= events.length - 1} onClick={() => setIndex(index + 1)}>Next scene</button><button onClick={() => setIndex(0)}>Return to live</button></div><div className="wall-story-grid"><div><span>WHAT HAPPENED</span><p>{scene.narrative}</p><span>WHAT REMAINS UNKNOWN</span><p>{scene.unknowns}</p><span>NEXT GOVERNED STEP</span><p>{scene.nextStep}</p></div><Receipt scene={scene} truth={truth}/></div></section><div className="wall-timeline" aria-label="Scene timeline">{events.length ? events.map((item, itemIndex) => <button key={`${text(item.event_type)}-${itemIndex}`} className={itemIndex === index ? "is-active" : ""} onClick={() => setIndex(itemIndex)}>{text(item.event_type).replaceAll("_", " ")}</button>) : <p>No trustworthy storyline exists.</p>}</div></main>; }
function Replay({ events, index, setIndex }: { events: TruthRecord[]; index: number; setIndex: (value: number) => void }) { const event = events[index] ?? null; const scene = mapEventToScene(event); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); useEffect(() => { if (!playing || !events.length) return; const timer = window.setInterval(() => setIndex(index >= events.length - 1 ? 0 : index + 1), 4000 / speed); return () => window.clearInterval(timer); }, [playing, speed, index, events.length, setIndex]); return <main className="wall-replay"><span>REPLAY / HISTORICAL PRESENTATION</span><h1>{event ? "Session timeline" : "No replay session available"}</h1><p>Historical badge: this view is presentation-only and never current activity.</p><div className="wall-replay-controls"><button disabled={!index} onClick={() => setIndex(Math.max(0, index - 1))}>Previous</button><button disabled={index >= events.length - 1} onClick={() => setIndex(Math.min(events.length - 1, index + 1))}>Next</button><button disabled={!events.length} onClick={() => setPlaying(!playing)}>{playing ? "Pause" : "Play"}</button><button onClick={() => setSpeed(speed === 2 ? .5 : speed * 2)}>Speed {speed}x</button></div><input aria-label="Historical timeline" type="range" min="0" max={Math.max(0, events.length - 1)} value={index} onChange={(event) => setIndex(Number(event.target.value))} /><div className="wall-timeline">{events.length ? events.map((item, itemIndex) => <button key={`${text(item.event_type)}-${itemIndex}`} className={itemIndex === index ? "is-active" : ""} onClick={() => setIndex(itemIndex)}><b>{text(item.event_type)}</b><span>{date(item.created_at)} · {text(item.case_id, "NO CASE")}</span></button>) : <p>UNKNOWN: no completed session or replayable event receipt was supplied.</p>}</div>{event && <Receipt scene={scene} truth={null}/>}</main>; }
function Receipt({ scene, truth }: { scene: Scene; truth: TruthResult | null }) { return <section className="wall-receipt-card"><span>SCENE RECEIPT</span><dl><dt>Why selected</dt><dd>{scene.reason}</dd><dt>Event/session</dt><dd>{text(scene.receipt.event_id ?? scene.receipt.case_id, "UNKNOWN")}</dd><dt>Timestamp</dt><dd>{date(scene.receipt.created_at)}</dd><dt>Source identity</dt><dd>{text(truth?.data.source_identity, "UNKNOWN")}</dd><dt>Authority</dt><dd>READ-ONLY · LIVE EXECUTION FALSE</dd></dl></section>; }
