/// <reference types="node" />
import assert from "node:assert/strict"; import test from "node:test";
import { latestFactoryOutputs, roomOutput, stationOutput } from "./museumLiveBinding.ts";
import type { ExpansionSnapshot } from "./ExpansionWingSnapshotContext.ts";
const snapshot = {schema_version:"x",authority:{broker_connectivity:false},sections:{books:{state:"CURRENT",data:{nav:10000,cash:10000,positions:0,transactions:0,orders:0,fills:0}},radar:{state:"CURRENT",data:{governed_universe_count:519,candidate_lineage_state:"UNAVAILABLE"}},candidate_conveyor:{state:"FAILED_CLOSED",data:{candidates:[]}},projection_activation:{state:"AVAILABLE",data:{reader_state:"ACTIVE",integrity_state:"VALID",hash_validation:"VALID",freshness_state:"CURRENT",sequence:582,publisher_state:"UNAVAILABLE",last_publication_time:"2026-09-06T00:00:00Z"}},market_session:{state:"AVAILABLE",data:{state:"MARKET_CLOSED_WEEKEND",source_generated_at:"2026-09-06T00:00:00Z"}},service_health:{state:"CURRENT",data:{backend_reachable:true}},authority_lock:{state:"AVAILABLE",data:{locked:true,broker:false,credential:false,ledger_write:false,live_execution:false,paper_order:false,provider:false}}}} as unknown as ExpansionSnapshot;
const overview={generated_at:"2026-09-06T00:00:00Z",cache:{freshness_state:"CURRENT"},factory:{availability:"AVAILABLE"},validation:{layers:{factory_telemetry:{payload:{health:{state:"HEALTHY"},cadence:{observation:{availability:"AVAILABLE",cadence_state:"ON_CADENCE",last_completed_at:"2026-09-06T00:00:00Z",next_due_at:"2026-09-06T00:15:00Z"},paper_trading:{availability:"AVAILABLE",cadence_state:"ON_CADENCE"},radar:{availability:"AVAILABLE",cadence_state:"ON_CADENCE"}},paper_fund:{snapshot_as_of:"2026-09-06T00:00:00Z"},recent_meaningful_events:[{event_type:"COMMITTEE_COMPLETE",created_at:"2026-09-04T00:00:00Z",case_id:"opaque-1"},{event_type:"COMMITTEE_COMPLETE",created_at:"2026-09-04T00:00:00Z",case_id:"opaque-1"},{event_type:"UNAPPROVED_RAW",created_at:"2026-09-04T00:01:00Z",prompt:"private"}]}}}}};
test("stations use authenticated scalar fields and preserve zero",()=>{assert.match(stationOutput("paper",snapshot,overview).value,/NAV 10000.*POS 0.*ORD 0/);assert.equal(stationOutput("publisher",snapshot,overview).value,"SEQUENCE 582 · PUBLISHER UNAVAILABLE");});
test("missing authenticated values never inherit fixture defaults",()=>{const missing=stationOutput("paper",{...snapshot,sections:{}} as ExpansionSnapshot,{});assert.equal(missing.value,"Authenticated source did not report this field");assert.equal(missing.blocker,"SANITIZED_SOURCE_UNAVAILABLE");});
test("Gallery room badges share the authenticated station mapping",()=>{assert.equal(roomOutput("portfolio",snapshot,overview).source,"/expansion-wing/snapshot · books");assert.equal(roomOutput("radar",snapshot,overview).count,519);});
test("receipt feed is allowlisted bounded and deduplicated",()=>{const feed=latestFactoryOutputs(overview,8);assert.equal(feed.length,1);assert.equal(feed[0]?.category,"COMMITTEE_COMPLETE");assert.doesNotMatch(JSON.stringify(feed),/prompt|private/);});
test("aggregate candidate count never creates identity",()=>{assert.equal(stationOutput("conveyor",snapshot,overview).count,0);assert.equal(roomOutput("radar",snapshot,overview).eventCategory,"RADAR_CYCLE");});
