import { useEffect, useRef, useState } from "react";
import { useExpansionWingSnapshot } from "./ExpansionWingSnapshotContext";
import { latestFactoryOutputs, linkPromotionReceipts } from "./museumLiveBinding";
import "./MuseumCaseLibrary.css";
import "./MuseumCaseLibraryReceipts.css";

type Row = Record<string, unknown>;
export type CaseFilter = "ALL" | "COMMITTEE" | "RISK" | "AWAITING_EVIDENCE" | "REJECTED" | "CLOSED" | "OUTCOMES" | "INCOMPLETE";
const FILTERS: readonly [CaseFilter,string][] = [["ALL","All"],["COMMITTEE","Committee"],["RISK","Risk"],["AWAITING_EVIDENCE","Awaiting Evidence"],["REJECTED","Rejected"],["CLOSED","Closed"],["OUTCOMES","Outcomes"],["INCOMPLETE","Incomplete"]];
const record=(value:unknown):Row=>value!==null&&typeof value==="object"&&!Array.isArray(value)?value as Row:{};
const rows=(value:unknown):Row[]=>Array.isArray(value)?value.filter((item):item is Row=>item!==null&&typeof item==="object"&&!Array.isArray(item)):[];
const value=(item:unknown)=>typeof item==="string"&&item.trim()?item:typeof item==="number"||typeof item==="boolean"?String(item):"UNAVAILABLE";
const list=(item:unknown)=>Array.isArray(item)&&item.length?item.map(value).join(" · "):"UNAVAILABLE";
const matches=(item:Row,filter:CaseFilter)=>filter==="ALL"||filter==="OUTCOMES"&&item.outcome_availability==="AVAILABLE"||filter==="INCOMPLETE"&&item.evidence_completeness!=="COMPLETE"||item.stage===filter;

export default function MuseumCaseLibrary({ initialFilter="ALL" }: { initialFilter?: CaseFilter }) {
  const {snapshot,sanitizedOverview}=useExpansionWingSnapshot(); const data=record(snapshot?.sections?.governed_cases?.data); const cases=rows(data.cases); const counts=record(data.counts);
  const receiptLinks=linkPromotionReceipts(latestFactoryOutputs(sanitizedOverview,8),cases);
  const [filter,setFilter]=useState<CaseFilter>(initialFilter); const [query,setQuery]=useState(""); const [selected,setSelectedState]=useState<Row|null>(null); const originRef=useRef<HTMLElement|null>(null);
  const caseFromHash=()=>{const match=window.location.hash.match(/^#cases\/([^/]+)$/); if(!match)return null; try{return decodeURIComponent(match[1]);}catch{return "";}};
  const restoreCase=()=>{const identity=caseFromHash(); setSelectedState(identity?cases.find((item)=>value(item.case_id)===identity)??{case_id:identity,status:"CASE UNAVAILABLE"}:null);};
  // The deferred restore synchronizes an external URL source without a synchronous effect update.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const timer=window.setTimeout(restoreCase,0); window.addEventListener("popstate",restoreCase); window.addEventListener("hashchange",restoreCase); return()=>{window.clearTimeout(timer);window.removeEventListener("popstate",restoreCase);window.removeEventListener("hashchange",restoreCase);};},[snapshot]);
  const setSelected=(item:Row|null)=>{if(item){originRef.current=document.activeElement as HTMLElement; const identity=value(item.case_id); window.history.pushState({museumMode:"cases",caseId:identity},"",`#cases/${encodeURIComponent(identity)}`); setSelectedState(item);}else{window.history.pushState({museumMode:"cases"},"","#cases");setSelectedState(null);requestAnimationFrame(()=>originRef.current?.focus());}};
  const visible=cases.filter((item)=>matches(item,filter)&&[item.case_id,item.ticker,item.title,item.stage,item.status].some((field)=>value(field).toLowerCase().includes(query.trim().toLowerCase())));
  const muFound=cases.some((item)=>item.ticker==="MU");
  return <main className="museum-case-library" aria-labelledby="case-library-title"><header><span>AUTHENTICATED CASE REGISTRY · READ ONLY</span><h1 id="case-library-title">Case Library</h1><p>Every row is anchored to an immutable browser-safe case identity. Missing evidence remains unavailable.</p><small>Source: /experience/factory-intelligence/overview · observed {value(data.source_observed_at)} · freshness {value(data.freshness_state)}</small></header>
    <section className="case-library-summary" aria-label="Authenticated case totals">{[["Total authenticated cases",data.total],["Active",counts.active],["Committee",counts.committee],["Risk",counts.risk],["Awaiting evidence",counts.awaiting_evidence],["Rejected",counts.rejected],["Closed",counts.closed],["Cases with outcomes",counts.with_outcomes],["Incomplete browser-safe details",counts.without_browser_details]].map(([label,count])=><article key={String(label)}><span>{String(label)}</span><strong>{value(count)}</strong></article>)}</section>
    <section className="case-library-controls"><nav aria-label="Case stage filters">{FILTERS.map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</nav><label>Search authenticated fields<input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Case ID, ticker, title, stage"/></label></section>
    {query.trim().toUpperCase()==="MU"&&!muFound?<aside className="case-library-mu"><strong>MU — No authenticated governed case found.</strong><p>MU exists as a discussed research thesis but is absent from the authoritative governed Case Registry. No case was fabricated or backfilled.</p></aside>:null}
    <p className="case-library-result-count">Showing {visible.length} of {cases.length} authenticated cases · {filter.replaceAll("_"," ")}</p>
    <section className="case-library-receipts" aria-label="Promotion receipt linkage"><header><strong>Promotion receipt linkage</strong><span>Exact immutable identity only</span></header>{receiptLinks.length?receiptLinks.map((link)=><article key={link.receipt.id}><b>{link.state}</b><span>{link.caseId ?? "No authenticated case identity"}</span><small>{link.reason}</small></article>):<p>No browser-safe OPPORTUNITY promotion receipt is available. Aggregate promotion counts never create case identities.</p>}</section>
    <section className="case-library-list" aria-label="Selectable authenticated cases">{visible.map((item)=><button key={value(item.case_id)} onClick={()=>setSelected(item)}><code>{value(item.case_id)}</code><strong>{value(item.ticker)} · {value(item.title)}</strong><span>{value(item.stage)} / {value(item.status)}</span><dl><div><dt>Updated</dt><dd>{value(item.updated_at)}</dd></div><div><dt>Committee</dt><dd>{value(item.committee_state)}</dd></div><div><dt>Risk</dt><dd>{value(item.risk_state)}</dd></div><div><dt>Paper eligible</dt><dd>{value(item.paper_eligibility)}</dd></div><div><dt>Outcome</dt><dd>{value(item.outcome_availability)}</dd></div><div><dt>Details</dt><dd>{value(item.evidence_completeness)}</dd></div><div><dt>Blocker</dt><dd>{list(item.blockers)}</dd></div></dl></button>)}</section>
    {!visible.length?<p className="case-library-empty">No authenticated cases match this filter or search.</p>:null}
    {selected?<div className="case-dossier-backdrop" role="dialog" aria-modal="true" aria-labelledby="case-dossier-title" onKeyDown={(event)=>{if(event.key==="Escape")setSelected(null)}}><section><button autoFocus onClick={()=>setSelected(null)} aria-label="Close case dossier">×</button><span>CASE DOSSIER · BROWSER-SAFE</span><h2 id="case-dossier-title">{value(selected.ticker)} · {value(selected.case_id)}</h2><dl>{[["Identity and lineage",selected.case_id],["Detection / origin",selected.originating_cycle_id],["Created",selected.created_at],["Updated",selected.updated_at],["Evidence state",selected.evidence_completeness],["Thesis",selected.thesis_summary],["Bear case",selected.bear_case_summary],["Professional observations",null],["Skeptic state",null],["Committee state",selected.committee_state],["Risk state",selected.risk_state],["Paper state",selected.position_state],["Outcome state",selected.outcome_availability],["Sanitized receipts",list(selected.receipt_categories)],["Missing fields",list(selected.blockers)],["Current blocker",list(selected.blockers)],["Next required action","COMPLETE BROWSER-SAFE EVIDENCE AND HUMAN REVIEW"]].map(([label,detail])=><div key={String(label)}><dt>{String(label)}</dt><dd>{value(detail)}</dd></div>)}</dl></section></div>:null}
  </main>;
}
