import { useEffect, useState } from "react";
import "./OperatingSuperbatch.css";

type JsonObject = Record<string, unknown>;
type Unified = { status?: string; operating_mode?: string; modules?: JsonObject[]; capital_readiness_blockers?: JsonObject[]; summary?: JsonObject; safety?: JsonObject };
type Qualification = { status?: string; rubric?: string; sample_ready?: boolean; paper_nav?: number; paper_positions?: number; paper_transactions?: number; complete_validation_sessions?: number; mature_5d_outcomes?: number; cumulative_return_pct?: number | null; max_drawdown_pct?: number | null; gates?: JsonObject[]; readiness_meaning?: string };
type Portfolio = { status?: string; nav?: number; cash?: number; cash_pct?: number | null; position_count?: number; gross_exposure_pct?: number | null; net_exposure?: number; top_position_weight_pct?: number | null; top_three_weight_pct?: number | null; max_drawdown_pct?: number | null; cumulative_return_pct?: number | null; positions?: JsonObject[]; measurement_gaps?: string[]; advisory_flags?: string[] };

function text(value: unknown, fallback = "—") { if (typeof value === "string" && value.trim()) return value; if (typeof value === "number" && Number.isFinite(value)) return String(value); if (typeof value === "boolean") return value ? "TRUE" : "FALSE"; return fallback; }
function pct(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? `${value.toFixed(2)}%` : "—"; }
function money(value: unknown) { return typeof value === "number" && Number.isFinite(value) ? value.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}) : "—"; }
async function load<T>(name: string): Promise<T> { const r = await fetch(`/${name}?ts=${Date.now()}`,{cache:"no-store",headers:{Accept:"application/json"}}); if(!r.ok) throw new Error(`${name} HTTP ${r.status}`); return r.json() as Promise<T>; }

export default function OperatingSuperbatch() {
  const [unified,setUnified]=useState<Unified|null>(null); const [qualification,setQualification]=useState<Qualification|null>(null); const [portfolio,setPortfolio]=useState<Portfolio|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{ let disposed=false; const refresh=async()=>{ try { const [u,q,p]=await Promise.all([load<Unified>("unified_production_browser.json"),load<Qualification>("paper_performance_qualification.json"),load<Portfolio>("portfolio_intelligence.json")]); if(!disposed){setUnified(u);setQualification(q);setPortfolio(p);setError(null);} } catch(reason){if(!disposed)setError(reason instanceof Error?reason.message:"Operating browser unavailable");} }; void refresh(); const timer=window.setInterval(()=>void refresh(),30000); return()=>{disposed=true;window.clearInterval(timer);};},[]);
  if(!unified||!qualification||!portfolio) return <section className="ops-shell ops-waiting"><span>BATCH 10A–10C · OPERATING SUPERBATCH</span><h2>{error?"OPERATING VIEW WARM-UP":"ASSEMBLING THE FIRM VIEW"}</h2><p>{error??"Waiting for unified paper, qualification and portfolio artifacts."}</p></section>;
  const summary=unified.summary??{}; const modules=unified.modules??[]; const gates=qualification.gates??[]; const positions=portfolio.positions??[];
  return <section className="ops-shell">
    <div className="ops-hero"><div><span>BATCH 10A · UNIFIED PRODUCTION BROWSER</span><h2>One firm. One operating picture. Zero hidden authority.</h2><p>“Production Browser” means the unified operating interface. The firm is still governed paper/research only; this screen cannot send orders, connect a broker or advance capital.</p></div><div className="ops-guard"><strong>GOVERNED PAPER ONLY</strong><span>HUMAN APPROVAL REQUIRED</span><em>LIVE EXECUTION FALSE</em></div></div>
    <div className="ops-safety"><span>BROWSER COMMAND AUTHORITY · FALSE</span><span>BACKEND WRITE · FALSE</span><span>BROKER AUTHORITY · FALSE</span><span>CAPITAL AUTHORITY · FALSE</span></div>
    <div className="ops-score"><article><span>MODULES</span><strong>{text(summary.module_count)}</strong></article><article><span>PAPER NAV</span><strong>{money(summary.paper_nav)}</strong></article><article><span>PAPER POSITIONS</span><strong>{text(summary.paper_positions,"0")}</strong></article><article><span>10B STATUS</span><strong className="ops-status">{text(summary.paper_qualification_status).replaceAll("_"," ")}</strong></article><article><span>READINESS BLOCKERS</span><strong>{text(summary.capital_readiness_blocker_count,"0")}</strong></article></div>
    <section className="ops-panel"><div className="ops-title"><div><span>10A · UNIFIED OPERATING MAP</span><h3>Everything important on one board</h3></div><strong>{text(unified.operating_mode).replaceAll("_"," ")}</strong></div><div className="ops-modules">{modules.map((row,i)=><article key={`${text(row.code)}-${i}`}><span>{text(row.code)}</span><strong>{text(row.name)}</strong><em>{text(row.status,"WAITING").replaceAll("_"," ")}</em></article>)}</div></section>

    <div className="ops-divider">10B · PAPER PERFORMANCE QUALIFICATION</div>
    <section className="ops-panel ops-qualification"><div className="ops-title"><div><span>QUALIFICATION RUBRIC</span><h3>{text(qualification.status).replaceAll("_"," ")}</h3></div><strong>{text(qualification.rubric)}</strong></div><p>{text(qualification.readiness_meaning)}</p><div className="ops-score six"><article><span>SESSIONS</span><strong>{text(qualification.complete_validation_sessions,"0")}</strong></article><article><span>TRANSACTIONS</span><strong>{text(qualification.paper_transactions,"0")}</strong></article><article><span>MATURE 5D</span><strong>{text(qualification.mature_5d_outcomes,"0")}</strong></article><article><span>RETURN</span><strong>{pct(qualification.cumulative_return_pct)}</strong></article><article><span>MAX DD</span><strong>{pct(qualification.max_drawdown_pct)}</strong></article><article><span>SAMPLE READY</span><strong>{text(qualification.sample_ready)}</strong></article></div><div className="ops-gates">{gates.map((row,i)=><article key={`${text(row.gate)}-${i}`} className={`is-${text(row.state,"WAITING").toLowerCase()}`}><strong>{text(row.gate).replaceAll("_"," ")}</strong><span>Observed · {text(row.observed)}</span><span>Required · {text(row.required)}</span><em>{text(row.state)}</em></article>)}</div></section>

    <div className="ops-divider">10C · PORTFOLIO INTELLIGENCE</div>
    <section className="ops-panel"><div className="ops-title"><div><span>GOVERNED PAPER BOOK</span><h3>{text(portfolio.status).replaceAll("_"," ")}</h3></div><strong>ADVISORY ONLY</strong></div><div className="ops-score six"><article><span>NAV</span><strong>{money(portfolio.nav)}</strong></article><article><span>CASH</span><strong>{money(portfolio.cash)}</strong><em>{pct(portfolio.cash_pct)}</em></article><article><span>POSITIONS</span><strong>{text(portfolio.position_count,"0")}</strong></article><article><span>GROSS EXPOSURE</span><strong>{pct(portfolio.gross_exposure_pct)}</strong></article><article><span>TOP POSITION</span><strong>{pct(portfolio.top_position_weight_pct)}</strong></article><article><span>CUM. RETURN</span><strong>{pct(portfolio.cumulative_return_pct)}</strong></article></div>{positions.length?<div className="ops-positions">{positions.map((row,i)=><article key={`${text(row.ticker)}-${i}`}><strong>{text(row.ticker)}</strong><span>{text(row.direction)}</span><span>Weight · {pct(row.weight_pct)}</span><span>P&L · {money(row.unrealized_pnl)}</span></article>)}</div>:<div className="ops-empty"><strong>CASH-ONLY WARM-UP</strong><p>No governed paper positions exist, so 10C correctly has no concentration, factor or correlation story to invent.</p></div>}<div className="ops-gaps"><strong>MEASUREMENT GAPS</strong>{(portfolio.measurement_gaps??[]).map(item=><span key={item}>{item}</span>)}</div></section>
    <div className="ops-footer"><span>10A · VIEW ONLY</span><span>10B · QUALIFICATION ONLY</span><span>10C · PORTFOLIO ADVISORY ONLY</span><span>LIVE CAPITAL · FALSE</span></div>{error?<div className="ops-warning">LATEST REFRESH WARNING · {error}</div>:null}
  </section>;
}
