import { useCallback, useEffect, useMemo, useState } from "react";
import { projectThesisIntegrity, thesisIntegrityTone, type ThesisMonitorProjectionInput } from "./thesisIntegrityProjection";
const API = "http://127.0.0.1:8002";
const ACTIVE_CASE_KEY = "iios.activeCaseId";
type DashboardCase = { case_id:string; topic:string; ticker?:string; health?:string; committee_disposition?:string; committee_confidence?:number; evidence_quality?:number; latest_return_pct?:number; latest_action?:string; monitoring_enabled?:boolean; };
type FactoryStatus = { portfolio?:{nav?:number|null;cash?:number|null;positions?:number|null;return_pct?:number|null;drawdown_pct?:number|null}; safety?:{all_invariants?:boolean;live_execution?:boolean} };
type History = { signal_ladder?:{current_stage?:string;next_requirements?:string[]} };
type Bank = { thesis_monitors?: ThesisMonitorProjectionInput[] };
type State = { cases:DashboardCase[]; factory:FactoryStatus|null; history:History|null; bank:Bank|null; online:boolean; caseId:string|null };
const ratioPct=(v?:number|null)=>v==null?"—":`${Math.round(v*100)}%`;
const pointPct=(v?:number|null)=>v==null?"—":`${v.toFixed(1)}%`;
const money=(v?:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const label=(v?:string)=>String(v||"UNKNOWN").replaceAll("_"," ");
const tone=(v?:string)=>{const s=String(v||"").toUpperCase();if(/BROKEN|INVALID|REJECT|BLOCK|NO_TRADE|LOCK/.test(s))return"iios-state-block";if(/WATCH|PENDING|EARLY|WAIT/.test(s))return"iios-state-watch";if(/INTACT|CLEAR|QUALIFIED|APPROVED|READY/.test(s))return"iios-state-clear";return"iios-state-idle";};
export default function PortfolioThesisWarRoom(){
 const[state,setState]=useState<State>({cases:[],factory:null,history:null,bank:null,online:false,caseId:window.localStorage.getItem(ACTIVE_CASE_KEY)});
 const load=useCallback(async()=>{const caseId=window.localStorage.getItem(ACTIVE_CASE_KEY);try{const[d,f]=await Promise.all([fetch(`${API}/monitoring/dashboard`),fetch(`${API}/factory-room/status`)]);if(!d.ok||!f.ok)throw new Error();const dashboard=await d.json() as{cases?:DashboardCase[]};const factory=await f.json() as FactoryStatus;let history:History|null=null,bank:Bank|null=null;if(caseId){const[h,b]=await Promise.all([fetch(`${API}/history/${caseId}`),fetch(`${API}/judgment-bank/${caseId}`)]);if(h.ok)history=await h.json() as History;if(b.ok)bank=await b.json() as Bank;}setState({cases:dashboard.cases||[],factory,history,bank,online:true,caseId});}catch{setState(c=>({...c,online:false,caseId}));}},[]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const t=window.setInterval(()=>void load(),10000);return()=>{window.clearTimeout(initial);window.clearInterval(t);};},[load]);
 const active=useMemo(()=>state.cases.find(x=>x.case_id===state.caseId)??null,[state.cases,state.caseId]);
 const latestThesis=useMemo(()=>state.bank?.thesis_monitors?.slice(-1)[0],[state.bank]);const integrity=projectThesisIntegrity(latestThesis);const signal=state.history?.signal_ladder?.current_stage;const next=state.history?.signal_ladder?.next_requirements?.[0]||active?.latest_action||"Continue governed monitoring";const portfolio=state.factory?.portfolio;const locked=state.factory?.safety?.live_execution===false;
 return <section className="portfolio-war-room"><div className="portfolio-war-room-head"><div><div className="portfolio-war-room-eyebrow">PORTFOLIO & THESIS WAR ROOM</div><h2>{active?.ticker||"PORTFOLIO"} · <span className={thesisIntegrityTone(integrity)}>{label(integrity)}</span></h2><p>{active?.topic||"Select an active case to connect thesis state to paper portfolio context."}</p></div><div className={state.online?"portfolio-war-room-live":"portfolio-war-room-offline"}>{state.online?"WAR ROOM LIVE":"WAR ROOM OFFLINE"}</div></div>
 <div className="portfolio-war-room-primary"><div><span>THESIS INTEGRITY</span><strong className={thesisIntegrityTone(integrity)}>{label(integrity)}</strong></div><div><span>COMMITTEE</span><strong className={tone(active?.committee_disposition)}>{label(active?.committee_disposition)}</strong></div><div><span>CONFIDENCE</span><strong>{ratioPct(active?.committee_confidence)}</strong></div><div><span>PORTFOLIO EXPOSURE</span><strong>{portfolio?.positions??"—"} positions · {money(portfolio?.nav)} NAV</strong></div><div><span>CAPITAL</span><strong className={locked?"iios-state-block":"iios-state-idle"}>{locked?"LIVE LOCKED":"VERIFY"}</strong></div></div>
 <div className="portfolio-war-room-grid"><div className="portfolio-war-room-panel"><div className="portfolio-war-room-label">PAPER PORTFOLIO</div><div className="portfolio-war-room-metrics"><div><span>NAV</span><strong>{money(portfolio?.nav)}</strong></div><div><span>CASH</span><strong>{money(portfolio?.cash)}</strong></div><div><span>POSITIONS</span><strong>{portfolio?.positions??"—"}</strong></div><div><span>RETURN</span><strong>{pointPct(portfolio?.return_pct)}</strong></div><div><span>DRAWDOWN</span><strong>{pointPct(portfolio?.drawdown_pct)}</strong></div></div></div><div className="portfolio-war-room-panel"><div className="portfolio-war-room-label">THESIS EVIDENCE</div><div className="portfolio-war-room-metrics"><div><span>INTEGRITY</span><strong className={thesisIntegrityTone(integrity)}>{label(integrity)}</strong></div><div><span>COMMITTEE</span><strong className={tone(active?.committee_disposition)}>{label(active?.committee_disposition)}</strong></div><div><span>CONFIDENCE</span><strong>{ratioPct(active?.committee_confidence)}</strong></div><div><span>EVIDENCE</span><strong>{ratioPct(active?.evidence_quality)}</strong></div><div><span>CASE RETURN</span><strong>{pointPct(active?.latest_return_pct)}</strong></div></div></div></div>
 <div className="portfolio-war-room-decision"><div><span>NEXT GOVERNED REQUIREMENT</span><strong>{next}{signal?` · signal ${label(signal)}`:""}</strong></div><div><span>CAPITAL AUTHORITY</span><strong className={locked?"portfolio-war-room-lock":"iios-state-idle"}>{locked?"LIVE CAPITAL LOCKED":"VERIFY SAFETY STATE"}</strong></div></div></section>;
}
