import { useEffect, useState } from "react";
import "./ReadinessSuperbatch.css";

type JsonObject=Record<string,unknown>;
type Stress={status?:string;paper_nav?:number;position_count?:number;current_regime_label?:string;scenarios?:JsonObject[];worst_scenario?:JsonObject;measurement_gaps?:string[];stress_contract?:string};
type Readiness={status?:string;gates?:JsonObject[];unresolved_gate_count?:number;paper_qualification_passed?:boolean;stress_gate_passed?:boolean;recommended_next_action?:string;readiness_meaning?:string};
type Firm={status?:string;operating_loop?:string[];modules?:JsonObject[];current_state?:JsonObject;institutionalization_gaps?:string[];governance_principles?:string[]};
function text(v:unknown,f="—"){if(typeof v==="string"&&v.trim())return v;if(typeof v==="number"&&Number.isFinite(v))return String(v);if(typeof v==="boolean")return v?"TRUE":"FALSE";return f}function pct(v:unknown){return typeof v==="number"&&Number.isFinite(v)?`${v.toFixed(2)}%`:"—"}function money(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}):"—"}
async function load<T>(name:string):Promise<T>{const r=await fetch(`/${name}?ts=${Date.now()}`,{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`${name} HTTP ${r.status}`);return r.json() as Promise<T>}
export default function ReadinessSuperbatch(){const[stress,setStress]=useState<Stress|null>(null);const[ready,setReady]=useState<Readiness|null>(null);const[firm,setFirm]=useState<Firm|null>(null);const[error,setError]=useState<string|null>(null);useEffect(()=>{let disposed=false;const refresh=async()=>{try{const[s,r,f]=await Promise.all([load<Stress>("capital_preservation_stress_lab.json"),load<Readiness>("governed_capital_readiness.json"),load<Firm>("institutional_investment_firm_os.json")]);if(!disposed){setStress(s);setReady(r);setFirm(f);setError(null)}}catch(reason){if(!disposed)setError(reason instanceof Error?reason.message:"Readiness view unavailable")}};void refresh();const timer=window.setInterval(()=>void refresh(),30000);return()=>{disposed=true;window.clearInterval(timer)}},[]);if(!stress||!ready||!firm)return <section className="rdy-shell rdy-waiting"><span>BATCH 10D–10F · READINESS SUPERBATCH</span><h2>{error?"READINESS WARM-UP":"ASSEMBLING THE CAPITAL DOSSIER"}</h2><p>{error??"Waiting for deterministic stress, readiness and institutional OS artifacts."}</p></section>;const scenarios=stress.scenarios??[];const gates=ready.gates??[];const modules=firm.modules??[];return <section className="rdy-shell">
<div className="rdy-hero"><div><span>BATCH 10D–10F · CAPITAL PRESERVATION + READINESS + FIRM OS</span><h2>Build the institution before you hand it money.</h2><p>The final engineering layer stress-tests the paper book, assembles the capital-readiness evidence dossier, and maps the institutional operating system. It does not authorize live capital.</p></div><div className="rdy-guard"><strong>LIVE CAPITAL NOT AUTHORIZED</strong><span>HUMAN + LEGAL GATES REQUIRED</span><em>LIVE EXECUTION FALSE</em></div></div><div className="rdy-safety"><span>AUTO FUND · FALSE</span><span>AUTO CONNECT BROKER · FALSE</span><span>AUTO ENABLE LIVE · FALSE</span><span>CAPITAL AUTHORITY · FALSE</span></div>
<div className="rdy-divider">10D · CAPITAL PRESERVATION & STRESS LAB</div><section className="rdy-panel"><div className="rdy-title"><div><span>DETERMINISTIC HYPOTHETICALS</span><h3>{text(stress.status).replaceAll("_"," ")}</h3></div><strong>{text(stress.current_regime_label,"REGIME WARM-UP").replaceAll("_"," ")}</strong></div><p>{text(stress.stress_contract)}</p><div className="rdy-score"><article><span>PAPER NAV</span><strong>{money(stress.paper_nav)}</strong></article><article><span>POSITIONS</span><strong>{text(stress.position_count,"0")}</strong></article><article><span>WORST STRESS</span><strong>{pct(stress.worst_scenario?.estimated_nav_change_pct)}</strong></article><article><span>FORECAST?</span><strong>NO</strong></article></div><div className="rdy-scenarios">{scenarios.map((row,i)=><article key={`${text(row.scenario)}-${i}`}><strong>{text(row.scenario).replaceAll("_"," ")}</strong><span>Shock · {pct(row.shock_pct)}</span><span>P&L · {money(row.estimated_pnl)}</span><span>NAV change · {pct(row.estimated_nav_change_pct)}</span><em>HYPOTHETICAL · NOT FORECAST</em></article>)}</div><div className="rdy-gaps"><strong>STRESS MEASUREMENT GAPS</strong>{(stress.measurement_gaps??[]).map(x=><span key={x}>{x}</span>)}</div></section>
<div className="rdy-divider">10E · GOVERNED CAPITAL READINESS</div><section className="rdy-panel"><div className="rdy-title"><div><span>READINESS DOSSIER</span><h3>{text(ready.status).replaceAll("_"," ")}</h3></div><strong>{text(ready.unresolved_gate_count,"0")} UNRESOLVED</strong></div><p>{text(ready.readiness_meaning)}</p><div className="rdy-gates">{gates.map((row,i)=><article key={`${text(row.gate)}-${i}`} className={`is-${text(row.state,"WAITING").toLowerCase()}`}><header><strong>{text(row.gate).replaceAll("_"," ")}</strong><em>{text(row.state).replaceAll("_"," ")}</em></header><p>{text(row.evidence)}</p><span>Owner · {text(row.owner).replaceAll("_"," ")}</span></article>)}</div><div className="rdy-next"><strong>NEXT ACTION</strong><span>{text(ready.recommended_next_action).replaceAll("_"," ")}</span></div></section>
<div className="rdy-divider">10F · INSTITUTIONAL INVESTMENT FIRM OS</div><section className="rdy-panel"><div className="rdy-title"><div><span>INSTITUTIONAL ARCHITECTURE</span><h3>{text(firm.status).replaceAll("_"," ")}</h3></div><strong>ARCHITECTURE ≠ REGULATORY STATUS</strong></div><div className="rdy-modules">{modules.map((row,i)=><article key={`${text(row.room)}-${i}`}><strong>{text(row.room).replaceAll("_"," ")}</strong><span>{text(row.systems)}</span><p>{text(row.purpose)}</p></article>)}</div><div className="rdy-two"><div><strong>GOVERNANCE PRINCIPLES</strong>{(firm.governance_principles??[]).map(x=><span key={x}>{x}</span>)}</div><div><strong>INSTITUTIONALIZATION GAPS</strong>{(firm.institutionalization_gaps??[]).map(x=><span key={x}>{x}</span>)}</div></div><div className="rdy-loop"><strong>OPERATING LOOP</strong><div>{(firm.operating_loop??[]).map((x,i)=><span key={`${x}-${i}`}>{String(i+1).padStart(2,"0")} · {x}</span>)}</div></div></section>
<div className="rdy-footer"><span>STRESS · HYPOTHETICAL ONLY</span><span>READINESS · DOSSIER ONLY</span><span>INSTITUTIONAL OS · ARCHITECTURE ONLY</span><span>LIVE EXECUTION · FALSE</span></div>{error?<div className="rdy-warning">LATEST REFRESH WARNING · {error}</div>:null}</section>}
