import { useCallback,useEffect,useMemo,useState } from "react";
import { getActiveCaseId, subscribeActiveCase } from "./activeCaseStore";
const API="http://127.0.0.1:8002";
type Thesis={thesis_status?:string;flags?:string[];falsifiers_triggered?:string[];catalyst_status?:string;observed_return_pct?:number|null;created_at?:string};type Reunderwrite={prior_thesis_status?:string;action?:string;created_at?:string};type Bank={thesis_monitors?:Thesis[];reunderwrites?:Reunderwrite[]};type Integrity="INTACT"|"EARLY_BUT_INTACT"|"MATERIAL_CHANGE"|"THESIS_BROKEN"|"UNKNOWN";
function project(latest?:Thesis):Integrity{if(!latest)return"UNKNOWN";const status=String(latest.thesis_status||"").toUpperCase(),flags=(latest.flags||[]).map(x=>String(x).toUpperCase());if(status==="THESIS_BROKEN"||flags.includes("FALSIFIER_TRIGGERED"))return"THESIS_BROKEN";if(status==="REUNDERWRITE_REQUIRED"||flags.some(f=>["CATALYST_MISSED","UPDATE_EVIDENCE_STALE","UPDATE_EVIDENCE_CONFLICT","DRAWDOWN_TRIGGERED"].includes(f)))return"MATERIAL_CHANGE";if(status==="INTACT"&&(latest.catalyst_status==="UNKNOWN"||flags.length>0))return"EARLY_BUT_INTACT";if(status==="INTACT")return"INTACT";return"UNKNOWN"}
const tone=(s:Integrity)=>s==="INTACT"?"iios-state-clear":s==="EARLY_BUT_INTACT"?"iios-state-watch":s==="MATERIAL_CHANGE"||s==="THESIS_BROKEN"?"iios-state-block":"iios-state-idle";
export default function ThesisIntegrityCommand(){const[bank,setBank]=useState<Bank|null>(null),[online,setOnline]=useState(false),[caseId,setCaseId]=useState<string|null>(()=>getActiveCaseId());const load=useCallback(async()=>{const id=getActiveCaseId();try{if(!id){setBank(null);setOnline(true);return;}const r=await fetch(`${API}/judgment-bank/${id}`);if(!r.ok)throw new Error();setBank(await r.json() as Bank);setOnline(true);}catch{setOnline(false)}},[]);
 useEffect(()=>subscribeActiveCase(id=>{setCaseId(id);window.setTimeout(()=>void load(),0);}),[load]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const t=window.setInterval(()=>void load(),10000);return()=>{window.clearTimeout(initial);window.clearInterval(t);}},[load]);
 const latest=useMemo(()=>bank?.thesis_monitors?.slice(-1)[0],[bank]);const integrity=project(latest);const latestRe=bank?.reunderwrites?.slice(-1)[0];const flags=latest?.flags||[];const falsifiers=latest?.falsifiers_triggered||[];
 return <section className="thesis-integrity-command"><div className="thesis-integrity-head"><div><div className="thesis-integrity-eyebrow">THESIS INTEGRITY CONTROL</div><h2>{caseId?<span className={tone(integrity)}>{integrity.replaceAll("_"," ")}</span>:"NO ACTIVE CASE"}</h2><p>Read-only projection from governed thesis monitors and re-underwrites. It does not create a second decision engine.</p></div><div className={online?"iios-state-clear":"iios-state-block"}>{online?"THESIS LEDGER LIVE":"THESIS LEDGER OFFLINE"}</div></div><div className="thesis-integrity-path">{(["INTACT","EARLY_BUT_INTACT","MATERIAL_CHANGE","THESIS_BROKEN"] as Integrity[]).map((s,i)=><div key={s} className={s===integrity?`active ${tone(s)}`:""}><span>{i+1}</span><strong>{s.replaceAll("_"," ")}</strong></div>)}</div><div className="thesis-integrity-grid"><div><span>CATALYST</span><strong>{latest?.catalyst_status||"—"}</strong></div><div><span>FLAGS</span><strong>{flags.length?flags.join(" · "):"NONE"}</strong></div><div><span>FALSIFIERS</span><strong className={falsifiers.length?"iios-state-block":"iios-state-clear"}>{falsifiers.length?falsifiers.join(" · "):"NONE TRIGGERED"}</strong></div><div><span>OBSERVED RETURN</span><strong>{latest?.observed_return_pct==null?"—":`${latest.observed_return_pct.toFixed(1)}%`}</strong></div><div><span>REUNDERWRITE ACTION</span><strong>{latestRe?.action||"—"}</strong></div></div><div className="thesis-integrity-consequence"><span>GOVERNED CONSEQUENCE</span><strong>{integrity==="THESIS_BROKEN"?"Exit shadow case / block new capital":integrity==="MATERIAL_CHANGE"?"Pause progression and re-underwrite":integrity==="EARLY_BUT_INTACT"?"Maintain watch; evidence still maturing":integrity==="INTACT"?"Continue governed monitoring":"Await thesis monitor"}</strong></div></section>}
