import { useCallback,useEffect,useMemo,useState } from "react";
import { getActiveCaseId, subscribeActiveCase } from "./activeCaseStore";
import { projectThesisIntegrity, type ThesisIntegrity, type ThesisMonitorProjectionInput } from "./thesisIntegrityProjection";
const API="http://127.0.0.1:8002";
type Thesis=ThesisMonitorProjectionInput;type Bank={thesis_monitors?:Thesis[]};type Capital={stage?:string;permissions?:{position_sizing_ready?:boolean;paper_authorization_ready?:boolean;paper_order_permission?:boolean;live_execution?:boolean};capital?:{decision?:string}};
const expected:Record<ThesisIntegrity,{reunderwrite:string;sizing:string;paper:string;live:string}>={INTACT:{reunderwrite:"MONITOR",sizing:"MAY PROCEED IF OTHER GATES PASS",paper:"MAY PROCEED IF AUTHORIZED",live:"LOCKED"},EARLY_BUT_INTACT:{reunderwrite:"WATCH",sizing:"HOLD / VERIFY",paper:"LOCKED UNTIL GATES PASS",live:"LOCKED"},MATERIAL_CHANGE:{reunderwrite:"REQUIRED",sizing:"BLOCKED",paper:"BLOCKED",live:"LOCKED"},THESIS_BROKEN:{reunderwrite:"EXIT / CLOSE",sizing:"BLOCKED",paper:"BLOCKED",live:"LOCKED"},UNKNOWN:{reunderwrite:"AWAIT STATE",sizing:"LOCKED",paper:"LOCKED",live:"LOCKED"}};
export default function ThesisCapitalConsequenceMatrix(){const[bank,setBank]=useState<Bank|null>(null),[capital,setCapital]=useState<Capital|null>(null),[caseId,setCaseId]=useState<string|null>(()=>getActiveCaseId()),[online,setOnline]=useState(false);const load=useCallback(async()=>{const id=getActiveCaseId();try{if(!id){setBank(null);setCapital(null);setOnline(true);return;}const b=await fetch(`${API}/judgment-bank/${id}`);if(!b.ok)throw new Error();setBank(await b.json() as Bank);const c=await fetch(`${API}/paper-capital/${id}/status`);setCapital(c.ok?await c.json() as Capital:null);setOnline(true);}catch{setOnline(false)}},[]);
 useEffect(()=>subscribeActiveCase(id=>{setCaseId(id);window.setTimeout(()=>void load(),0);}),[load]);
 useEffect(()=>{const initial=window.setTimeout(()=>void load(),0);const t=window.setInterval(()=>void load(),10000);return()=>{window.clearTimeout(initial);window.clearInterval(t);};},[load]);
 const latest=useMemo(()=>bank?.thesis_monitors?.slice(-1)[0],[bank]);const state=projectThesisIntegrity(latest),rule=expected[state];const actualSizing=capital?.permissions?.position_sizing_ready?"READY":"LOCKED";const actualPaper=capital?.permissions?.paper_order_permission?"READY":"LOCKED";const actualLive=capital?.permissions?.live_execution?"ENABLED":"LOCKED";
 return <section className="thesis-capital-matrix"><div className="thesis-capital-matrix-head"><div><div className="thesis-capital-matrix-eyebrow">THESIS → CAPITAL CONSEQUENCE</div><h2>{caseId?state.replaceAll("_"," "):"NO ACTIVE CASE"}</h2><p>Expected policy consequence versus actual governed capital permissions. This surface never grants authority.</p></div><div className={online?"iios-state-clear":"iios-state-block"}>{online?"CONSEQUENCE CHECK LIVE":"CHECK OFFLINE"}</div></div><div className="thesis-capital-matrix-grid"><div><span>REUNDERWRITE</span><strong>{rule.reunderwrite}</strong><small>Expected from thesis integrity</small></div><div><span>SIZING</span><strong>{rule.sizing}</strong><small>Actual: {actualSizing}</small></div><div><span>PAPER ORDER</span><strong>{rule.paper}</strong><small>Actual: {actualPaper}</small></div><div><span>LIVE CAPITAL</span><strong className="iios-state-block">{rule.live}</strong><small>Actual: {actualLive}</small></div><div><span>CAPITAL STAGE</span><strong>{capital?.stage?.replaceAll("_"," ")||"NOT EVALUATED"}</strong><small>{capital?.capital?.decision||"No capital decision"}</small></div></div></section>}
